[default]
DISCORD_TOKEN = ""

YAHOO_LEAGUE_ID = ""
YAHOO_LEAGUE_TYPE = ""
YAHOO_KEY = ""
YAHOO_SECRET = ""

OAUTH_ACCESS_TOKEN = ""
OAUTH_GUID = ""
OAUTH_REFRESH_TOKEN = ""
OAUTH_TOKEN_TIME = ""
OAUTH_TOKEN_TYPE = ""
